-- DROP TABLE IF EXISTS user;
-- DROP TABLE IF EXISTS package;
-- DROP TABLE IF EXISTS Vote;

CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS package (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  link  TEXT NOT NULL,
  title  VARCHAR(40) NOT NULL,
  tagline  VARCHAR(60) NOT NULL,
  topics  Text NOT NULL,
  active INTEGER DEFAULT 0,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES user (id)
);


CREATE TABLE IF NOT EXISTS Vote (
  user_id INTEGER NOT NULL,
  package_id INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id),
  FOREIGN KEY (user_id) REFERENCES user (id)
)